// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sghztuggogphsoghhrzc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNnaHp0dWdnb2dwaHNvZ2hocnpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU2NzQxMjUsImV4cCI6MjA1MTI1MDEyNX0.12ZWpu2XKUHwn3DyZNWCEt0yZ7EpixfSn0slux5QJN4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);